### ISSUE TITLE
With blockchain disabled, daemon still expects a valid AGENT_CONTRACT_ADDRESS

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/alpha-daemon#3]
I've tried setting `AGENT_CONTRACT_ADDRESS` to `None`, the empty string, and removing the key from from the configuration file.

```
# snetd --config-path config/snetd_face_detect_server_config.json
Traceback (most recent call last):
  File "/usr/local/bin/snetd", line 25, in <module>
    main()
  File "/usr/local/bin/snetd", line 20, in main
    daemon = SingularityNetDaemon()
  File "/usr/local/lib/python3.6/site-packages/snetd_alpha/daemon.py", line 40, in __init__
    self.chain = BlockchainClient(self.app)
  File "/usr/local/lib/python3.6/site-packages/snetd_alpha/blockchain.py", line 32, in __init__
    self.agent = self.w3.eth.contract(address=self.to_checksum_address(config.AGENT_CONTRACT_ADDRESS), abi=abi)
  File "/usr/local/lib/python3.6/site-packages/snetd_alpha/blockchain.py", line 57, in to_checksum_address
    return self.w3.toChecksumAddress(address)
  File "/usr/local/lib/python3.6/site-packages/eth_utils/address.py", line 113, in to_checksum_address
    norm_address = to_normalized_address(address)
  File "/usr/local/lib/python3.6/site-packages/eth_utils/address.py", line 68, in to_normalized_address
    "Unknown format {}, attempted to normalize to {}".format(address, hex_address)
ValueError: Unknown format , attempted to normalize to 0x
```

**Comment by ferrouswheel** [comment]
This was my fault. While I had set the `AGENT_CONTRACT_ADDRESS` to `None`, I still had a junk address in `PRIVATE_KEY`. Ensuring these were both `None` allows the daemon to start successfully.
